principal = 34.25

[[instances]]
id = "e2587bad-25c5-4171-84cb-08ca1ce7c70e"
symbol = "btcusdt"
mode = "or"
stop_loss = 0.1
principal = 10.5

[[instances.strategies]]
id = "fe808f31-04b7-4119-8d89-6650a3e9695e"
type = "rsi"
interval = "2h"
period = 14
buy_threshold = 20.0
sell_threshold = 80.0

[[instances]]
id = "9748c940-0209-422c-9846-6e6cc219c2d3"
symbol = "bnbusdt"
mode = "or"
stop_loss = 0.1
principal = 10.5

[[instances.strategies]]
id = "4b73a5df-b4c3-458d-9d24-022d169d9c35"
type = "rsi"
interval = "2h"
period = 14
buy_threshold = 20.0
sell_threshold = 80.0
