## 一个实例仅会持有一单，这单没卖出前不会下买单。
## 止损模式： 下跌百分比，卖单超过n分钟没卖出重新挂单，重新挂单超过三次，以保本价卖出。保本价由引擎计算。

principal = 34.25 # 可操作的本金

[[instances]]
symbol = 'btcusdt' # 交易对
mode = 'or' # 策略触发模式
principal = 10.5 # 可操作的本金
stop_loss = 0.1 # 止损下跌幅度
[[instances.strategies]]
type = 'rsi' # 策略类型 rsi atr boll macd 
interval = '2h' # 数据维度
period = 14 # 数据周期
buy_threshold = 20.0 # 购买阈值
sell_threshold = 80.0 # 出售阈值

[[instances]]
symbol = 'bnbusdt'
mode = 'or'
principal = 10.5
stop_loss = 0.1 # 止损下跌幅度
[[instances.strategies]]
type = 'rsi'
interval = '2h'
period = 14
buy_threshold = 20.0
sell_threshold = 80.0
